name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH agent
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -t rsa ${{ secrets.HOST }} >> ~/.ssh/known_hosts
          ssh-agent
          ssh-add ~/.ssh/id_rsa

      - name: Deploy using SSH
        run: |
          ssh ${{ secrets.USERNAME }}@${{ secrets.HOST }} "cd /var/www/Projek/ && git pull origin main && git status && npm install --only=prod"
